Vagrant.configure("2") do |config|
  # config.trigger.before :up do |trigger|
  #   trigger.info = "Creating 'NATSwitch' Hyper-V switch if it does not exist..."
  #   trigger.run = {privileged: "true", powershell_elevated_interactive: "true", path: "./create-nat-hyperv-switch.ps1"}
  # end

  # config.trigger.before :reload do |trigger|
  #   trigger.info = "Setting Hyper-V switch to 'NATSwitch' to allow for static IP..."
  #   trigger.run = {privileged: "true", powershell_elevated_interactive: "true", path: "./set-hyperv-switch.ps1"}
  # end

  config.vm.box_check_update = false
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider "hyperv"
  config.vm.network "public_network", bridge: "VagrantNet"
  config.vm.hostname = "XenialVagrantMachine"

  config.vm.provider "hyperv" do |h|
    h.vm_integration_services = {
      guest_service_interface: true
    }
    h.vmname = "XenialVagrantMachine"
    h.memory = 512
    h.cpus = 1
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx
    sudo systemctl status nginx
    sudo systemctl enable nginx
    sudo systemctl start nginx
    sudo ufw allow 'Nginx Full'
  SHELL

  # config.vm.provision "shell", path: "./configure-static-ip.sh"
  # config.vm.provision :reload

  # config.vm.provider "virtualbox" do |vb|
  #   vb.name = "XenialVagrantMachine"
  #   vb.gui = true
  #   vb.memory = "1024"
  #   vb.cpus = 1
  #   config.vm.network "private_network", type: "dhcp", name: "vboxnet_vagrant"
  #   # config.vm.network "private_network", ip: "192.168.50.4"
  #   vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  # end
end